from moviepy.editor import VideoFileClip
from shortwizard.config import root_assets

_1_Grinning_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '1_Grinning Face.mov', has_mask=True)
_2_Beaming_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '2_Beaming Face.mov', has_mask=True)
_3_Face_With_Tears = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '3_Face With Tears.mov', has_mask=True)
_4_Rolling_on_the_Floor = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '4_Rolling on the Floor.mov', has_mask=True)
_5_Grinning_Face_With_Big_Eyes = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '5_Grinning Face With Big Eyes.mov', has_mask=True)
_6_Grinning_Face_With_Smiling_Eyes = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '6_Grinning Face With Smiling Eyes.mov', has_mask=True)
_7_Grinning_Face_With_Sweat = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '7_Grinning Face With Sweat.mov', has_mask=True)
_8_Grinning_Squinting_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '8_Grinning Squinting Face.mov', has_mask=True)
_9_Winking_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '9_Winking Face.mov', has_mask=True)
_10_Smiling_Face_Blushing = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '10_Smiling Face Blushing.mov', has_mask=True)
_11_Face_Savoring_Food = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '11_Face Savoring Food.mov', has_mask=True)
_12_Smiling_Face_With_Sunglasses = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '12_Smiling Face With Sunglasses.mov', has_mask=True)
_13_Smiling_Face_With_Heart_Eyes = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '13_Smiling Face With Heart-Eyes.mov', has_mask=True)
_14_Face_Blowing_a_Kiss = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '14_Face Blowing a Kiss.mov', has_mask=True)
_15_Kissing_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '15_Kissing Face.mov', has_mask=True)
_16_Kissing_Face_With_Smiling_Eyes = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '16_Kissing Face With Smiling Eyes.mov', has_mask=True)
_17_Kissing_Face_With_Closed_Eyes = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '17_Kissing Face With Closed Eyes.mov', has_mask=True)
_18_Blushing_Closed_eyes = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '18_Blushing Closed eyes.mov', has_mask=True)
_19_Slightly_Smiling_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '19_Slightly Smiling Face.mov', has_mask=True)
_20_Hugging_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '20_Hugging Face.mov', has_mask=True)
_21_Star_Struck = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '21_Star-Struck.mov', has_mask=True)
_22_Thinking_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '22_Thinking Face.mov', has_mask=True)
_23_Face_With_Raised_Eyebrow = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '23_Face With Raised Eyebrow.mov', has_mask=True)
_24_Neutral_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '24_Neutral Face.mov', has_mask=True)
_25_Expressionless_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '25_Expressionless Face.mov', has_mask=True)
_26_Face_Without_Mouth = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '26_Face Without Mouth.mov', has_mask=True)
_27_Face_With_Rolling_Eyes = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '27_Face With Rolling Eyes.mov', has_mask=True)
_28_Smirking_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '28_Smirking Face.mov', has_mask=True)
_29_Persevering_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '29_Persevering Face.mov', has_mask=True)
_30_Sad_but_Relieved_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '30_Sad but Relieved Face.mov', has_mask=True)
_31_Face_With_Open_Mouth = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '31_Face With Open Mouth.mov', has_mask=True)
_32_Zipper_Mouth_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '32_Zipper-Mouth Face.mov', has_mask=True)
_33_Hushed_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '33_Hushed Face.mov', has_mask=True)
_34_Sleepy_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '34_Sleepy Face.mov', has_mask=True)
_35_Tired_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '35_Tired Face.mov', has_mask=True)
_36_Sleeping_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '36_Sleeping Face.mov', has_mask=True)
_37_Relieved_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '37_Relieved Face.mov', has_mask=True)
_38_Face_With_Tongue = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '38_Face With Tongue.mov', has_mask=True)
_39_Winking_Face_With_Tongue = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '39_Winking Face With Tongue.mov', has_mask=True)
_40_Squinting_Face_With_Tongue = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '40_Squinting Face With Tongue.mov', has_mask=True)
_41_Drooling_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '41_Drooling Face.mov', has_mask=True)
_42_Unamused_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '42_Unamused Face.mov', has_mask=True)
_43_Downcast_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '43_Downcast Face.mov', has_mask=True)
_44_Pensive_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '44_Pensive Face.mov', has_mask=True)
_45_Confused_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '45_Confused Face.mov', has_mask=True)
_46_Upside_Down_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '46_Upside-Down Face.mov', has_mask=True)
_47_Money_Mouth_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '47_Money-Mouth Face.mov', has_mask=True)
_48_Astonished_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '48_Astonished Face.mov', has_mask=True)
_49_Frowning_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '49_Frowning Face.mov', has_mask=True)
_50_Slightly_Frowning_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '50_Slightly Frowning Face.mov', has_mask=True)
_51_Confounded_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '51_Confounded Face.mov', has_mask=True)
_52_Disappointed_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '52_Disappointed Face.mov', has_mask=True)
_53_Worried_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '53_Worried Face.mov', has_mask=True)
_54_Face_With_Steam_From_Nose = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '54_Face With Steam From Nose.mov', has_mask=True)
_55_Crying_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '55_Crying Face.mov', has_mask=True)
_56_Loudly_Crying_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '56_Loudly Crying Face.mov', has_mask=True)
_57_Frowning_Face_With_Open_Mouth = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '57_Frowning Face With Open Mouth.mov', has_mask=True)
_58_Anguished_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '58_Anguished Face.mov', has_mask=True)
_59_Fearful_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '59_Fearful Face.mov', has_mask=True)
_60_Weary_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '60_Weary Face.mov', has_mask=True)
_61_Exploding_Head = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '61_Exploding Head.mov', has_mask=True)
_62_Grimacing_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '62_Grimacing Face.mov', has_mask=True)
_63_Anxious_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '63_Anxious Face.mov', has_mask=True)
_64_Face_Screaming_in_Fear = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '64_Face Screaming in Fear.mov', has_mask=True)
_65_Flushed_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '65_Flushed Face.mov', has_mask=True)
_66_Zany_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '66_Zany Face.mov', has_mask=True)
_67_Dizzy_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '67_Dizzy Face.mov', has_mask=True)
_68_Pouting_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '68_Pouting Face.mov', has_mask=True)
_69_Angry_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '69_Angry Face.mov', has_mask=True)
_70_Face_With_Symbols_on_Mouth = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '70_Face With Symbols on Mouth.mov', has_mask=True)
_71_Face_With_Medical_Mask = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '71_Face With Medical Mask.mov', has_mask=True)
_72_Face_With_Thermometer = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '72_Face With Thermometer.mov', has_mask=True)
_73_Face_With_Head_Bandage = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '73_Face With Head-Bandage.mov', has_mask=True)
_74_Nauseated_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '74_Nauseated Face.mov', has_mask=True)
_75_Face_Vomiting = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '75_Face Vomiting.mov', has_mask=True)
_76_Sneezing_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '76_Sneezing Face.mov', has_mask=True)
_77_Smiling_Face_With_Halo = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '77_Smiling Face With Halo.mov', has_mask=True)
_78_Cowboy_Hat = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '78_Cowboy Hat.mov', has_mask=True)
_79_Clown_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '79_Clown Face.mov', has_mask=True)
_80_Lying_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '80_Lying Face.mov', has_mask=True)
_81_Shushing_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '81_Shushing Face.mov', has_mask=True)
_82_Face_With_Hand_Over_Mouth = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '82_Face With Hand Over Mouth.mov', has_mask=True)
_83_Face_With_Monocle = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '83_Face With Monocle.mov', has_mask=True)
_84_Nerd_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '84_Nerd Face.mov', has_mask=True)
_85_Hot_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '85_Hot Face.mov', has_mask=True)
_86_Partying_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '86_Partying Face.mov', has_mask=True)
_87_Pleading_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '87_Pleading Face.mov', has_mask=True)
_88_Woozy_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '88_Woozy Face.mov', has_mask=True)
_89_Cold_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '89_Cold Face.mov', has_mask=True)
_90_Smiling_Face_With_Hearts = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '90_Smiling Face With Hearts.mov', has_mask=True)
_91_Smiling_Face_With_Horns = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '91_Smiling Face With Horns.mov', has_mask=True)
_92_Angry_Face_With_Horns = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '92_Angry Face With Horns.mov', has_mask=True)
_93_Grinning_Cat_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '93_Grinning Cat Face.mov', has_mask=True)
_94_Grinning_Cat_Face_With_Smiling_Eyes = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '94_Grinning Cat Face With Smiling Eyes.mov', has_mask=True)
_95_Cat_Face_With_Tears_of_Joy = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '95_Cat Face With Tears of Joy.mov', has_mask=True)
_96_Smiling_Cat_Face_With_Heart_Eyes = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '96_Smiling Cat Face With Heart-Eyes.mov', has_mask=True)
_97_Cat_Face_With_Wry_Smile = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '97_Cat Face With Wry Smile.mov', has_mask=True)
_98_Kissing_Cat_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '98_Kissing Cat Face.mov', has_mask=True)
_99_Weary_Cat_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '99_Weary Cat Face.mov', has_mask=True)
_100_Crying_Cat_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '100_Crying Cat Face.mov', has_mask=True)
_101_Pouting_Cat_Face = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '101_Pouting Cat Face.mov', has_mask=True)
_102_See_No_Evil_Monkey = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '102_See-No-Evil Monkey.mov', has_mask=True)
_103_Hear_No_Evil_Monkey = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '103_Hear-No-Evil Monkey.mov', has_mask=True)
_104_Speak_No_Evil_Monkey = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '104_Speak-No-Evil Monkey.mov', has_mask=True)
_105_Red_Heart = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '105_Red Heart.mov', has_mask=True)
_106_Broken_Heart = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '106_Broken Heart.mov', has_mask=True)
_107_Revolving_Hearts = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '107_Revolving Hearts.mov', has_mask=True)
_108_Two_Hearts = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '108_Two Hearts.mov', has_mask=True)
_109_Flexed_Biceps = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '109_Flexed Biceps.mov', has_mask=True)
_110_Shaka_hand = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '110_Shaka hand.mov', has_mask=True)
_111_Waving_Hand = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '111_Waving Hand.mov', has_mask=True)
_112_OK_Hand = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '112_OK Hand.mov', has_mask=True)
_113_Victory_Hand = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '113_Victory Hand.mov', has_mask=True)
_114_Crossed_Fingers = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '114_Crossed Fingers.mov', has_mask=True)
_115_Sign_of_the_Horns = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '115_Sign of the Horns.mov', has_mask=True)
_116_Love_You_Gesture = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '116_Love-You Gesture.mov', has_mask=True)
_117_Thumbs_Up = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '117_Thumbs Up.mov', has_mask=True)
_118_Thumbs_Down = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '118_Thumbs Down.mov', has_mask=True)
_119_Vulcan_Salute = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '119_Vulcan Salute.mov', has_mask=True)
_120_Clapping_Hands = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '120_Clapping Hands.mov', has_mask=True)
_121_Folded_Hands = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '121_Folded Hands.mov', has_mask=True)
_122_Middle_Finger = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '122_Middle Finger.mov', has_mask=True)
_123_Backhand_Index_Pointing_Right = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '123_Backhand Index Pointing Right.mov', has_mask=True)
_124_Raising_Hands = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '124_Raising Hands.mov', has_mask=True)
_125_Eyes = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '125_Eyes.mov', has_mask=True)
_126_Man_Shrugging = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '126_Man Shrugging.mov', has_mask=True)
_127_Woman_Shrugging = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '127_Woman Shrugging.mov', has_mask=True)
_128_Man_Facepalming = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '128_Man Facepalming.mov', has_mask=True)
_129_Woman_Facepalming = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '129_Woman Facepalming.mov', has_mask=True)
_130_Man_Gesturing_No = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '130_Man Gesturing No.mov', has_mask=True)
_131_Woman_Gesturing_No = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '131_Woman Gesturing No.mov', has_mask=True)
_132_Fire = VideoFileClip(root_assets /'video' / 'emotes' / 'pack1' / '132_Fire.mov', has_mask=True)
